pool:
  vmImage: 'ubuntu-20.04'

trigger: none
pr: none
schedules:
- cron: '0 3 * * *' # Everyday at 3am (Certs run at 2am)
  branches:
    include:
    - trunk

stages:
- stage: okta_preview
  displayName: Okta Preview
  jobs:
  - deployment:
    displayName: Update Okta
    environment: Preview - Okta
    variables:
    - group: Okta-Preview
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: Update Okta
            inputs:
              azureSubscription: Azure - HomeValet Platform Non-Production
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |  
                export VAULT_NAME=hv-dev-001-kv-ops-01
                export CERT_NAME=auth-homevalet-dev
                export OKTA_API_TOKEN=$(OktaApiToken)
                export OKTA_ORG_NAME=homevalet
                export OKTA_BASE_URL=oktapreview.com
                export OKTA_CUSTOM_AUTH_HOSTNAME=auth.homevalet.dev

                ./update-okta.sh

- stage: okta
  displayName: Okta
  jobs:
  - deployment:
    displayName: Update Okta
    environment: Okta
    variables:
    - group: Okta
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: Update Okta
            inputs:
              azureSubscription: Azure - HomeValet Platform Production
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |  
                export VAULT_NAME=hv-prd-001-kv-ops-01
                export CERT_NAME=auth-homevalet-co
                export OKTA_API_TOKEN=$(OktaApiToken)
                export OKTA_ORG_NAME=homevalet
                export OKTA_BASE_URL=okta.com
                export OKTA_CUSTOM_AUTH_HOSTNAME=auth.homevalet.co

                ./update-okta.sh
